import type { Program, ProgramDetail, Review, SupportInfo } from '@/types';

export const PROGRAMS: Program[] = [
  {
    id: 1,
    tag: '회복 프로그램',
    dDay: 'D-13',
    title: '천천히, 다시 만나는 일상',
    org: '경기 청년센터',
    status: '모집 중',
    bg: 'var(--card-blue)',
    chips: ['전체 신청 가능', '경기', '온·오프라인'],
    weeks: '8주 · 주 1회',
    deadline: '마감 2026.05.18',
  },
  {
    id: 2,
    tag: '온라인 모임',
    dDay: 'D-5',
    title: '방 안에서 세상으로,\n온라인 살롱',
    org: '나나센터 수원',
    status: '모집 중',
    bg: 'var(--card-yellow)',
    chips: ['전체 신청 가능', '경기', '온라인'],
    weeks: '4주 · 주 1회',
    deadline: '마감 2026.05.10',
  },
  {
    id: 3,
    tag: '원데이',
    dDay: '곧오픈',
    title: '글쓰기로 나를 정리하는 시간',
    org: '서울 청년허브',
    status: '모집 예정',
    bg: 'var(--card-orange)',
    chips: ['모집 예정', '서울', '온·오프라인'],
    weeks: '하루 · 4시간',
    deadline: '마감 2026.06.01',
    statusVariant: 'soon',
  },
  {
    id: 4,
    tag: '회복 프로그램',
    dDay: 'D-17',
    title: '식물 돌봄, 나도 돌봄',
    org: '부산 청년정책연구원',
    status: '모집 중',
    bg: 'var(--card-purple)',
    chips: ['전체 신청 가능', '부산', '오프라인'],
    weeks: '8주 · 주 1회',
    deadline: '마감 2026.05.22',
  },
  {
    id: 5,
    tag: '사회 적응',
    dDay: 'D-10',
    title: '취업 전, 나를\n알아가는 워크숍',
    org: '인천 청년센터',
    status: '모집 중',
    bg: 'var(--card-mustard)',
    chips: ['전체 신청 가능', '인천', '오프라인'],
    weeks: '8주 · 주 2회',
    deadline: '마감 2026.05.15',
  },
  {
    id: 6,
    tag: '온라인 모임',
    dDay: 'D-25',
    title: '늦은 밤 라디오, 청년 사연함',
    org: '광주 청년재단',
    status: '모집 중',
    bg: 'var(--card-lemon)',
    chips: ['전체 신청 가능', '광주', '온라인'],
    weeks: '4주 · 주 1회',
    deadline: '마감 2026.05.30',
  },
  {
    id: 7,
    tag: '회복 프로그램',
    dDay: '마감',
    title: '동네 한 바퀴, 산책 클럽',
    org: '대전 청년정책본부',
    status: '모집 중',
    bg: 'var(--card-pink)',
    chips: ['마감', '대전', '오프라인'],
    weeks: '6주 · 주 1회',
    deadline: '마감 2026.04.10',
    statusVariant: 'closed',
  },
  {
    id: 8,
    tag: '온라인 모임',
    dDay: '곧오픈',
    title: '게임으로 만나는 또래 살롱',
    org: '강원 청년허브',
    status: '모집 예정',
    bg: 'var(--card-mint)',
    chips: ['모집 예정', '강원', '온라인'],
    weeks: '8주 · 주 1회',
    deadline: '마감 2026.06.10',
    statusVariant: 'soon',
  },
];

export const PROGRAM_DETAIL: ProgramDetail = {
  intro: '아주 작은 외출에서 시작해, 또래와 함께 일상의 리듬을 천천히 되찾아가는 8주 프로그램.',
  description:
    '집 밖으로 나오는 첫걸음에 필요한 것들을 함께 마련해, 처음 4주는 1:1 동행으로 시작해 점차 소그룹 활동으로 옮겨갑니다. 끝과 길이, 본인의 속도에 맞춰 참여할 수 있어요.',
  qualification:
    '현재 사회적 고립 또는 은둔 상태에 있는 만 19~34세 청년으로, 일상 회복과 관계 경험을 희망하는 분이면 누구나 신청 가능합니다. 학력, 경력, 소득 제한 없이 참여하실 수 있습니다.',
  curriculum: [
    { weeks: '1~2주차', desc: '1:1 동행 프로그램 — 매니저와 함께 가까운 장소 방문, 외출 연습' },
    { weeks: '3~4주차', desc: '소그룹 활동 진입 — 3~4명 소그룹으로 카페/공원 방문' },
    { weeks: '5~6주차', desc: '문화 활동 체험 — 영화관, 전시회 등 문화공간 방문' },
    { weeks: '7~8주차', desc: '재입 활동 — 혼자 또는 또래와 함께 자율 활동 계획 및 실천' },
  ],
  org: {
    name: '경기 청년재단',
    region: '경기',
    phone: '031-123-4567',
    kakao: '@경기청년재단',
    homepage: 'https://open.kakao.com/example',
    email: 'support@example.or.kr',
  },
};

export const FILTER_OPTIONS: Record<string, string[]> = {
  region: ['서울', '부산', '대구', '인천', '광주', '대전', '울산', '세종', '경기', '강원', '충청', '전라', '경상', '제주'],
  level: ['일상 회복', '사회 복귀', '관계 형성'],
  mode: ['온라인', '오프라인', '온·오프라인'],
  period: ['1회(원데이)', '2회-4회', '5회 이상'],
  status: ['현재 신청 가능', '모집 예정', '마감'],
  people: ['1:1 상담', '여러명'],
};

export const FILTER_LABELS: Record<string, string> = {
  region: '지역',
  level: '참여 동기',
  mode: '온/오프라인',
  period: '참여 기간',
  status: '모집 상태',
  people: '참가 인원',
};

export const REVIEWS: Review[] = [
  { id: 1, name: '박○○', program: '천천히, 다시 만나는 일상', text: '혼자라고 생각했는데, 비슷한 친구들을 만나서 용기가 생겼어요.', avatar: '🌱' },
  { id: 2, name: '김○○', program: '온라인 살롱', text: '집에서도 참여할 수 있어서 부담이 없었고, 조금씩 나아지는 느낌이에요.', avatar: '🌙' },
  { id: 3, name: '이○○', program: '식물 돌봄, 나도 돌봄', text: '식물을 키우면서 저도 같이 돌봄을 받는 것 같았어요.', avatar: '🌿' },
  { id: 4, name: '최○○', program: '취업 전 워크숍', text: '나 자신을 알아가는 시간이 정말 필요했는데 딱이었어요.', avatar: '✨' },
  { id: 5, name: '정○○', program: '늦은 밤 라디오', text: '밤에 외롭지 않게 함께할 수 있는 공간이 생긴 것 같아요.', avatar: '📻' },
];

export const SUPPORT_INFO: SupportInfo[] = [
  {
    id: 1,
    title: '청년 월세 지원',
    category: '주거',
    description: '고립·은둔청년의 주거 안정을 위한 월세 보조금 지원',
    eligibility: '만 19~39세, 중위소득 150% 이하',
    benefit: '월 최대 20만원, 최대 12개월',
    contact: '주민센터 방문 또는 복지로',
  },
  {
    id: 2,
    title: '심리상담 바우처',
    category: '상담',
    description: '전문 심리상담사와 1:1 개인상담 지원',
    eligibility: '만 19~34세, 소득 기준 없음',
    benefit: '연 12회, 회당 5만원 지원',
    contact: '정신건강복지센터 031-000-0000',
  },
  {
    id: 3,
    title: '사회참여 프로그램',
    category: '관계',
    description: '또래 소그룹 활동, 문화체험 등 사회 참여 기회 제공',
    eligibility: '만 19~39세, 6개월 이상 고립 상태',
    benefit: '프로그램 전액 무료',
    contact: '나와나망 플랫폼 온라인 신청',
  },
];
